# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b907517b34168307083de5b22b37cd98311eab4cc8a6fe5ab9317fbec1be5eaf9df6f8aab0d503f6c81eb8f40beaef108e1f11c3a72a62d51354b94d313afb3

test:
  secret_key_base: bc788b33843df1cb2d7fb9a7666e52e8d9bf067e3545552156432841357af13c1a87762b1cdbcfc3d510df275f5158c6c2c789aa3eef2ef6127b8aed1e22f603

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
